force-app/main/default/objects/grc__Policy__c/grc__Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/grc__Policy__c/fields/Content_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Document_Id__c</fullName>
    <description>This field holds the salesforce ID of the ContentDocument which has been uploaded as a Policy Document through custom lightning component</description>
    <label>Content Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Version__c/Policy_Version__c.object-meta.xml
<CustomObject>
    <label>Policy Version</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Policy Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentVersionTriggerHandlerTest.cls
/**
*	@description : Test Class for content version trigger handler
**/
@isTest(seeAllData=false)
private with sharing class ContentVersionTriggerHandlerTest {
	
	/**
	*	@description : Set up test data
	**/
	@testSetup
	static void setUpTestData(){
		// create policies 
		List<grc__Policy__c> policiesToCreate = new List<grc__Policy__c>{new grc__Policy__c(Name='Test Policy - 1')};
		insert policiesToCreate;
		policiesToCreate = [SELECT Id FROM grc__Policy__c];
		System.assertEquals(1, policiesToCreate.size(), 'One Policy must be created.');
	}

	/**
	*	@description : test content version trigger
	**/
	@isTest static void test_contentTriggerHandler(){
		Test.startTest();
		// check before inserting file 
		System.assertEquals(0,[SELECT count() FROM Policy_Version__c],'No policy version record created.');
		// get policies
		List<grc__Policy__c> policiesList = [SELECT Id, Content_Document_Id__c FROM grc__Policy__c LIMIT 1]; 
		// create content documents 
		List<ContentVersion> contentVersionsList = new List<ContentVersion>{new ContentVersion(Title='Google.com',VersionData=Blob.valueOf('Test Content'),IsMajorVersion=true,PathOnClient='Penguins.jpg')};
		insert contentVersionsList;
		// get content document id
		contentVersionsList = [SELECT Id, Title, ContentDocumentId, VersionNumber FROM ContentVersion WHERE Id = :contentVersionsList[0].Id LIMIT 1];
		// create content document links 
		List<ContentDocumentLink> contentDocumentLinksList = new List<ContentDocumentLink>{new ContentDocumentLink(LinkedEntityId=policiesList[0].Id,ContentDocumentId=contentVersionsList[0].ContentDocumentId,ShareType='V',Visibility='AllUsers')};
		insert contentDocumentLinksList;
        // update content document ids to policy 
        policiesList[0].Content_Document_Id__c = contentVersionsList[0].ContentDocumentId;
        update policiesList;

        // check after updating inserting file 
		System.assertEquals(1,[SELECT count() FROM Policy_Version__c],'A policy version record created.');
		Test.stopTest();
	}
}