force-app/main/default/objects/grc__Policy__c/grc__Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/grc__Policy__c/fields/Content_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Document_Id__c</fullName>
    <description>This field holds the salesforce ID of the ContentDocument which has been uploaded as a Policy Document through custom lightning component</description>
    <label>Content Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Version__c/Policy_Version__c.object-meta.xml
<CustomObject>
    <label>Policy Version</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Policy Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Version__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>grc__Policy__c</referenceTo>
    <relationshipLabel>Policy Versions</relationshipLabel>
    <relationshipName>Policy_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Version__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version number of the policy document for this distribution.</description>
    <inlineHelpText>The version number of the policy document for this distribution.</inlineHelpText>
    <label>Version</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContentVersionHelper.cls
/**
* @description Trigger helper for content version
**/
public with sharing class ContentVersionHelper {

	/**
	* @description Method to populate the map of content document ids by content version ids
	* @param contentVersionsList List of content version records
	* @return Map<Id, ContentVersion> map of content document ids by content version records
	*/
	public static Map<Id, ContentVersion> fetchContentDocumentIdByContentVersionMap(List<ContentVersion> contentVersionsList){
		Map<Id, ContentVersion> contentDocumentByContentVersionMap = new Map<Id, ContentVersion>();
		for(ContentVersion contentVersion : contentVersionsList){
			contentDocumentByContentVersionMap.put(contentVersion.ContentDocumentId,contentVersion);
		}
		return contentDocumentByContentVersionMap;
	}
    
    /**
	* @description Method to get linked entity ids from content documents links
	* @param sObjectTypesList List of linked sobject types to look for
	* @param contentDocumentIds List of content document ids
	* @return Set<Id> List of linked entity ids
	*/
	public static Set<Id> getLinkedEntityIds(Set<String> sObjectTypesList, Set<Id> contentDocumentIds){
		Set<Id> linkedEntityIds = new Set<Id>();
		// get the content documents 
		List<ContentDocumentLink> contentDocumentLinksList = [SELECT ContentDocumentId, LinkedEntityId, LinkedEntity.Type FROM ContentDocumentLink 
																	WHERE ContentDocumentId IN: contentDocumentIds LIMIT 50000];
		for(ContentDocumentLink contentDocumentLink : contentDocumentLinksList){
			if(sObjectTypesList.contains(contentDocumentLink.LinkedEntity.Type)) linkedEntityIds.add(contentDocumentLink.LinkedEntityId);
		}	
		return linkedEntityIds;
	}


    /**
	* @description Method to populate the map of policy ids to lastet content version
	* @param policyIds List of policy ids
	* @param contentDocumentByContentVersionMap map of content document ids by content version records
	* @return Map<Id, Integer> map of policy ids by latest content version
	*/
	public static Map<Id,Integer> getPolicyVersionsMap(Set<Id> policyIds,Map<Id, ContentVersion> contentDocumentByContentVersionMap){
		Map<Id, Integer> policyByVersionMap = new Map<Id, Integer>();
		Map<Id, Id> contentDocumentByPoliciesMap = getContentDocumentIdsFromPolicies(policyIds);
		for(Id contentDocumentId : contentDocumentByPoliciesMap.keySet()){
			if(contentDocumentByContentVersionMap.containsKey(contentDocumentId)){
				policyByVersionMap.put(contentDocumentByPoliciesMap.get(contentDocumentId),Integer.valueOf(contentDocumentByContentVersionMap.get(contentDocumentId).VersionNumber));
			}
		}
		return policyByVersionMap;
	}


	/**
	* @description Method to get content document ids from policies
	* @param policyIds List of policy ids
	* @return Map<Id, Id> map of content document ids by policy ids
	*/
	@testVisible
	private static Map<Id,Id> getContentDocumentIdsFromPolicies(Set<Id> policyIds){
		Map<Id, Id> contentDocumentByPoliciesMap = new Map<Id, Id>();
		for(grc__Policy__c policy : [SELECT Id, Content_Document_Id__c FROM grc__Policy__c WHERE Content_Document_Id__c != null AND Id IN: policyIds LIMIT 20000]){
			contentDocumentByPoliciesMap.put(policy.Content_Document_Id__c,policy.Id);
		}
		return contentDocumentByPoliciesMap;
	}

	/**
	* @description Method to create policy version 
	* @param policyByVersionMapmap of policy ids by latest content version
	*/
	public static void createPolicyVersion(Map<Id, Integer> policyByVersionMap){
		List<Policy_Version__c> policyVersionsList = new List<Policy_Version__c>();
		for(Id policyId : policyByVersionMap.keySet()){
			policyVersionsList.add(new Policy_Version__c(Policy__c=policyId,Version__c=policyByVersionMap.get(policyId)));
		}
		try{
			if(!policyVersionsList.isEmpty()) insert policyVersionsList;
		}catch(Exception ex){
			throw new PolicyDistributionException(ex.getMessage());
		}
	}
}