force-app/main/default/objects/grc__Policy__c/grc__Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/grc__Policy__c/fields/Content_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Document_Id__c</fullName>
    <description>This field holds the salesforce ID of the ContentDocument which has been uploaded as a Policy Document through custom lightning component</description>
    <label>Content Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Version__c/Policy_Version__c.object-meta.xml
<CustomObject>
    <label>Policy Version</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Policy Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Version__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>grc__Policy__c</referenceTo>
    <relationshipLabel>Policy Versions</relationshipLabel>
    <relationshipName>Policy_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContentDocumentHelper.cls
/**
* @description Provide helper methods for Content Document
**/
public with sharing class ContentDocumentHelper {

    /**
    * @description Method to validate the content documents before deletion
    * @param       contentDocuments List of content document records
    */
    public static void validateDocumentDeletion(Map<Id,sobject> contentDocumentsMap){
        Map<Id, Id> policyIdByContentDocumentIdMap = new Map<Id, Id>();
        Set<Id> contentDocumentIds = contentDocumentsMap.keySet();
        List<ContentDocumentLink> contentDocumentLinks = [SELECT LinkedEntityId,ContentDocumentId FROM ContentDocumentLink 
                                                                   WHERE ContentDocumentId IN:contentDocumentIds LIMIT 50000];
        for(ContentDocumentLink cdl : contentDocumentLinks){
            policyIdByContentDocumentIdMap.put(cdl.LinkedEntityId,cdl.ContentDocumentId);
        }
        List<grc__Policy__c> policies = [SELECT Id,Content_Document_Id__c,(SELECT Id FROM Policy_Versions__r LIMIT 1) FROM grc__policy__c WHERE Id IN:policyIdByContentDocumentIdMap.keySet()];   
        for(grc__Policy__c policy : policies){
            if(policy.Content_Document_Id__c == policyIdByContentDocumentIdMap.get(policy.Id) && policy.Policy_Versions__r.size() > 0 ){
                if(contentDocumentsMap.containsKey(policy.Content_Document_Id__c)){
                    contentDocumentsMap.get(policy.Content_Document_Id__c).addError(System.Label.Policy_Document_Deletion_Error);
                }
            }
        }
    }
}