force-app/main/default/objects/grc__Policy__c/grc__Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/grc__Policy__c/fields/Content_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Document_Id__c</fullName>
    <description>This field holds the salesforce ID of the ContentDocument which has been uploaded as a Policy Document through custom lightning component</description>
    <label>Content Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Notification__c/Policy_Notification__c.object-meta.xml
<CustomObject>
    <label>Policy Notification</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Policy Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Notification__c/fields/Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Policy_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy Version</label>
    <referenceTo>Policy_Version__c</referenceTo>
    <relationshipLabel>Notified Users</relationshipLabel>
    <relationshipName>Notified_Users</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Version__c/Policy_Version__c.object-meta.xml
<CustomObject>
    <label>Policy Version</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Policy Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Version__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>grc__Policy__c</referenceTo>
    <relationshipLabel>Policy Versions</relationshipLabel>
    <relationshipName>Policy_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyVersionHelper.cls
/**
* @description Policy Version Helper
**/
public with sharing class PolicyVersionHelper {
	
	/**
	* @description Method to create policy notification record for each policy shared user
	* @param policyVersionsList List of policy version records
	*/
	public static void createPolicyNotifications(List<Policy_Version__c> policyVersionsList){
		List<Policy_Notification__c> policyNotificationsToCreate = new List<Policy_Notification__c>();
		Set<Id> policyIds = getPolicyIds(policyVersionsList);
		Map<Id, grc__Policy__c> policiesMap = new Map<Id, grc__Policy__c>([SELECT Id, (SELECT UserOrGroupId FROM Shares WHERE RowCause =: PolicyDistributionHelper.POLICY_APEX_SHARING_REASON) FROM grc__Policy__c]);
		for(Policy_Version__c policyVersion : policyVersionsList){
			if(policiesMap.containsKey(policyVersion.Policy__c)){
				for(grc__Policy__Share policyShare : policiesMap.get(policyVersion.Policy__c).Shares){
					policyNotificationsToCreate.add(new Policy_Notification__c(Policy_Version__c=policyVersion.Id,OwnerId=policyShare.UserOrGroupId));
				}
			}
		}
		try{
			if(!policyNotificationsToCreate.isEmpty()) insert policyNotificationsToCreate;
		}catch(Exception ex){
			throw new PolicyDistributionException(ex.getMessage());
		}
	}

	/**
	* @description Method to delete content docuemnts and remove content document id from policies
	* @param policyVersionsList List of policy version records
	*/
	public static void deleteContentDocuments(List<Policy_Version__c> policyVersionsList){
		List<ContentDocument> contentDocumentsToDelete = new List<ContentDocument>();
		Set<Id> policyIds = getPolicyIds(policyVersionsList);
		Map<Id, grc__Policy__c> policiesMap = new Map<Id, grc__Policy__c>([SELECT Id, Content_Document_Id__c, (SELECT Id FROM Policy_Versions__r LIMIT 1) FROM grc__Policy__c WHERE Id IN: policyIds
																				AND Content_Document_Id__c != null]);
		// delete content document and update policies
		for(grc__Policy__c policy : policiesMap.values()){
			if(policy.Policy_Versions__r.isEmpty()){
				contentDocumentsToDelete.add(new ContentDocument(Id=policy.Content_Document_Id__c));
				policy.Content_Document_Id__c = null;
			}
		}
		try{
			if(!contentDocumentsToDelete.isEmpty()) {
				if(Schema.sObjectType.ContentDocument.isDeletable()) {
					delete contentDocumentsToDelete;
				} else {
					throw new PolicyDistributionException(System.Label.Error_Unable_To_Delete_ContentDocument);
				}
				update policiesMap.values();
			}
		}catch(Exception ex){
			throw new PolicyDistributionException(ex.getMessage());
		}
	}

	/**
	* @description Method to get policy ids from policy version
	* @param policyVersionsList List of policy version records
	* @return Set<Id> Set of policy ids
	*/
	@testVisible
	private static Set<Id> getPolicyIds(List<Policy_Version__c> policyVersionsList){
		Set<Id> policyIds = new Set<Id>();
		for(Policy_Version__c policyVersion : policyVersionsList){
			policyIds.add(policyVersion.Policy__c);
		}
		return policyIds; 
	}
}