force-app/main/default/objects/grc__Policy__c/grc__Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/grc__Policy__c/fields/Content_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Document_Id__c</fullName>
    <description>This field holds the salesforce ID of the ContentDocument which has been uploaded as a Policy Document through custom lightning component</description>
    <label>Content Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Notification__c/Policy_Notification__c.object-meta.xml
<CustomObject>
    <label>Policy Notification</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Policy Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Notification__c/fields/Policy_Read__c.field-meta.xml
<CustomField>
    <fullName>Policy_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Policy Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Notification__c/fields/Policy_Version__c.field-meta.xml
<CustomField>
    <fullName>Policy_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy Version</label>
    <referenceTo>Policy_Version__c</referenceTo>
    <relationshipLabel>Notified Users</relationshipLabel>
    <relationshipName>Notified_Users</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Version__c/Policy_Version__c.object-meta.xml
<CustomObject>
    <label>Policy Version</label>
    <nameField>
        <displayFormat>PV-{00000}</displayFormat>
        <label>Policy Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Version__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>grc__Policy__c</referenceTo>
    <relationshipLabel>Policy Versions</relationshipLabel>
    <relationshipName>Policy_Versions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyTriggerHandlerTest.cls
/**
 * @description Test Class for PolicyTriggerHandler Trigger
 **/
@isTest(SeeAllData = false)
private with sharing class PolicyTriggerHandlerTest {

	private static List<User> usersList;
	
	/**
	*	@description : Set up test data
	**/
	@testSetup
	static void setUpTestData(){
		// create policies 
		List<grc__Policy__c> policiesToCreate = new List<grc__Policy__c>{new grc__Policy__c(Name = 'Test Policy 1')};
		insert policiesToCreate;

		// Create policy Version
		List<Policy_Version__c> policyVersionsList = new List<Policy_Version__c>{new Policy_Version__c(Policy__c=policiesToCreate[0].Id)};
		insert policyVersionsList;

		// create notified users
		List<Policy_Notification__c> policyNotificationsList = new List<Policy_Notification__c>{new Policy_Notification__c(Policy_Version__c=policyVersionsList[0].Id,OwnerId=UserInfo.getUserId(),Policy_Read__c=false)};
		insert policyNotificationsList;

		policiesToCreate = [SELECT Id FROM grc__Policy__c];
        System.assertEquals(1, policiesToCreate.size(), 'One Policy must be created.');   
        policyVersionsList = [SELECT Id FROM Policy_Version__c];
        System.assertEquals(1, policyVersionsList.size(), 'One Policy Version must be created.');  
		policyNotificationsList = [SELECT Id FROM Policy_Notification__c];
		System.assertEquals(1, policyNotificationsList.size(), 'One Policy Notification must be created.');
	}

	/**
	 * @description Method to update Policy
	 * @return	  grc__Policy__c
	 **/
	static grc__Policy__c updatePolicy() {
		grc__Policy__c policy = new grc__Policy__c(Name = 'P1');
		insert policy;
		List<ContentDocumentLink> cdl = createContentDocument(policy.Id);
		policy.Content_Document_Id__c = cdl[0].ContentDocumentId;
		update policy;
		return policy;
	}
	/**
	 * @description Method to create policy content documents
	 * @return	  List of ContentDocumentLink
	 **/
	static List<ContentDocumentLink> createContentDocument(Id policyId) {
		// create content documents 
		List<ContentVersion> contentVersionsList = new List<ContentVersion>{new ContentVersion(Title='Google.com',VersionData=Blob.valueOf('Test Content'),IsMajorVersion=true,PathOnClient='Penguins.jpg')};
		insert contentVersionsList;
		 // get content document id
		contentVersionsList = [SELECT Id, Title, ContentDocumentId, VersionNumber FROM ContentVersion WHERE Id = :contentVersionsList[0].Id LIMIT 1];
		// create content document links 
		List<ContentDocumentLink> contentDocumentLinksList = new List<ContentDocumentLink>{new ContentDocumentLink(LinkedEntityId=policyId,ContentDocumentId=contentVersionsList[0].ContentDocumentId,ShareType='V',Visibility='AllUsers')};
		insert contentDocumentLinksList;
		return contentDocumentLinksList;
	}
	/**
	 * @description Method to test create a new policy
	 **/
	@isTest static void updateExistingPolicy() {
		grc__Policy__c newPolicy = UpdatePolicy();
		System.Assert(newPolicy.Content_Document_Id__c != null, 'Content Document has been associated with policy');
	}
}